import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { FaTwitter, FaLinkedin, FaFacebook, FaInstagram } from "react-icons/fa";
import { Home, FileQuestionMark, BookAIcon } from "lucide-react";
import { useTheme } from "../ThemeContext";
const menuItems = [
    { name: "Home", path: "/", icon: _jsx(Home, { className: "w-5 h-5 inline mr-2" }) },
    { name: "About", path: "/About", icon: _jsx(FileQuestionMark, { className: "w-5 h-5 inline mr-2" }) },
    { name: "Meetings", path: "/Meetings", icon: _jsx(BookAIcon, { className: "w-5 h-5 inline mr-2" }) },
];
const Footer = () => {
    const { theme } = useTheme();
    return (_jsxs("footer", { style: { backgroundColor: theme["base-100"], color: theme["base-content"], borderTop: `1px solid ${theme["base-300"]}` }, children: [_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-20 py-10 flex flex-col sm:flex-row justify-between gap-8 sm:gap-0", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h1", { className: "text-xl font-bold mb-2", style: { color: theme.primary }, children: "Computing & Innovation Society" }), _jsx("p", { className: "text-sm sm:text-base", style: { color: theme["base-content"] }, children: "Laikipia University \u2013 Official meeting minutes archive maintained by the Secretary General." })] }), _jsx("div", { className: "flex-1 flex flex-col sm:flex-row justify-center gap-6 flex-wrap", children: menuItems.map((item) => (_jsxs(Link, { to: item.path, className: "flex items-center gap-1 transition hover:brightness-90", style: { color: theme["base-content"] }, children: [item.icon, " ", item.name] }, item.name))) }), _jsxs("div", { className: "flex-1 flex flex-col items-start sm:items-end gap-3", children: [_jsxs("p", { className: "text-sm", style: { color: theme["base-content"] }, children: ["Contact:", " ", _jsx("a", { href: "mailto:info@computinginnovation.lu", className: "transition hover:brightness-90", style: { color: theme.primary }, children: "info@computinginnovation.lu" })] }), _jsxs("div", { className: "flex gap-4 mt-2 text-xl", style: { color: theme.primary }, children: [_jsx("a", { href: "https://twitter.com/", target: "_blank", rel: "noopener noreferrer", className: "transition hover:text-blue-500", children: _jsx(FaTwitter, {}) }), _jsx("a", { href: "https://www.linkedin.com/", target: "_blank", rel: "noopener noreferrer", className: "transition hover:text-blue-700", children: _jsx(FaLinkedin, {}) }), _jsx("a", { href: "https://www.facebook.com/", target: "_blank", rel: "noopener noreferrer", className: "transition hover:text-blue-600", children: _jsx(FaFacebook, {}) }), _jsx("a", { href: "https://www.instagram.com/", target: "_blank", rel: "noopener noreferrer", className: "transition hover:text-pink-500", children: _jsx(FaInstagram, {}) })] })] })] }), _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-20 py-4 text-sm text-center sm:text-left", style: { color: theme["base-content"], borderTop: `1px solid ${theme["base-300"]}` }, children: ["\u00A9 ", new Date().getFullYear(), " Computing & Innovation Society of Laikipia University. All rights reserved."] })] }));
};
export default Footer;
