import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { useGetAllMeetingsQuery } from "../../Features/Apis/meetingApis";
import { useTheme } from "../../ThemeContext";
const features = [
    { icon: "📄", title: "Browse Meetings", desc: "Access all official meetings quickly." },
    { icon: "🔍", title: "Search Topics", desc: "Find meetings by topic, date, or attendee." },
    { icon: "⬇️", title: "Download PDFs", desc: "Save meeting details for reference or offline use." },
];
const LandingPage = () => {
    const { theme } = useTheme();
    const { data: meetings, isLoading, isError } = useGetAllMeetingsQuery(undefined);
    const latestMeetings = meetings
        ? [...meetings].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).slice(0, 3)
        : [];
    const fadeUp = { hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.6 } } };
    return (_jsxs("div", { className: "font-sans", style: { backgroundColor: theme["base-100"], color: theme["base-content"] }, children: [_jsxs(motion.section, { className: "py-10 px-4 text-center sm:py-12 sm:px-6 lg:px-20", initial: "hidden", animate: "visible", variants: { visible: { transition: { staggerChildren: 0.2 } } }, children: [_jsx(motion.h1, { className: "text-3xl sm:text-4xl lg:text-5xl font-bold mb-3 sm:mb-4", style: { color: theme.primary }, variants: fadeUp, children: "Access Official Meetings" }), _jsx(motion.p, { className: "text-base sm:text-lg lg:text-xl mb-6 sm:mb-8", style: { color: theme.secondary }, variants: fadeUp, children: "Browse, search, and download meeting details recorded by the Secretary General." }), _jsx(motion.div, { variants: fadeUp, children: _jsx(Link, { to: "/meetings", className: "px-4 py-2 sm:px-6 sm:py-3 text-base sm:text-lg font-semibold rounded-lg transition hover:brightness-90", style: { backgroundColor: theme.primary, color: theme["base-100"] }, children: "View Latest Meetings" }) })] }), _jsxs("section", { className: "py-8 px-4 sm:py-10 sm:px-6 text-center", children: [_jsx(motion.h2, { className: "text-2xl sm:text-3xl font-bold mb-6 sm:mb-8", style: { color: theme.primary }, initial: { opacity: 0 }, animate: { opacity: 1, transition: { duration: 0.8 } }, children: "Key Features" }), _jsx(motion.div, { className: "flex flex-col sm:flex-row justify-center gap-4 sm:gap-6", initial: "hidden", animate: "visible", variants: { visible: { transition: { staggerChildren: 0.2 } } }, children: features.map((feature, idx) => (_jsxs(motion.div, { className: "p-4 rounded-xl shadow-md w-full sm:w-64 transition hover:shadow-lg cursor-pointer", style: { backgroundColor: theme["base-200"], color: theme["base-content"] }, variants: fadeUp, whileHover: { scale: 1.05 }, children: [_jsx("div", { className: "text-3xl sm:text-4xl mb-2", children: feature.icon }), _jsx("h3", { className: "text-lg sm:text-xl font-semibold mb-1", style: { color: theme.primary }, children: feature.title }), _jsx("p", { className: "text-sm sm:text-base", style: { color: theme["base-content"] }, children: feature.desc })] }, idx))) })] }), _jsxs("section", { className: "py-8 px-4 sm:py-10 sm:px-6 text-center", children: [_jsx(motion.h2, { className: "text-2xl sm:text-3xl font-bold mb-6 sm:mb-8", style: { color: theme.primary }, initial: { opacity: 0 }, animate: { opacity: 1, transition: { duration: 0.8 } }, children: "How It Works" }), _jsx(motion.div, { className: "flex flex-col sm:flex-row justify-center gap-3 sm:gap-5 flex-wrap", initial: "hidden", animate: "visible", variants: { visible: { transition: { staggerChildren: 0.15 } } }, children: [
                            "Browse or search meetings by date or attendee.",
                            "Click to view full meeting details and discussions.",
                            "Download or save meeting details for future reference."
                        ].map((step, idx) => (_jsxs(motion.div, { className: "p-3 sm:p-4 w-full sm:w-64 rounded-xl border transition hover:shadow-md cursor-pointer", style: { borderColor: theme["base-300"], backgroundColor: theme["base-200"], color: theme["base-content"] }, variants: fadeUp, whileHover: { scale: 1.03 }, children: [_jsxs("div", { className: "text-xl sm:text-2xl font-bold mb-1", style: { color: theme.primary }, children: ["Step ", idx + 1] }), _jsx("p", { className: "text-sm sm:text-base", children: step })] }, idx))) })] }), _jsxs("section", { className: "py-8 px-4 sm:py-10 sm:px-6 text-center", children: [_jsx(motion.h2, { className: "text-2xl sm:text-3xl font-bold mb-6 sm:mb-8", style: { color: theme.primary }, initial: { opacity: 0 }, animate: { opacity: 1, transition: { duration: 0.8 } }, children: "Latest Meetings" }), isLoading && _jsx("p", { style: { color: theme.secondary }, children: "Loading meetings..." }), isError && _jsx("p", { className: "text-red-500", children: "Error fetching meetings." }), _jsx(motion.div, { className: "flex flex-col sm:flex-row justify-center gap-3 sm:gap-4 flex-wrap", initial: "hidden", animate: "visible", variants: { visible: { transition: { staggerChildren: 0.2 } } }, children: latestMeetings.map((meeting) => (_jsxs(motion.div, { className: "p-3 sm:p-4 rounded-xl shadow-md w-full sm:w-72 flex flex-col gap-2 transition hover:shadow-lg cursor-pointer", style: { backgroundColor: theme["base-200"], color: theme["base-content"] }, variants: fadeUp, whileHover: { scale: 1.03 }, children: [_jsx("h3", { className: "text-lg sm:text-xl font-semibold mb-1", style: { color: theme.primary }, children: meeting.title }), _jsx("p", { className: "mb-2 sm:mb-3 text-sm sm:text-base", style: { color: theme.secondary }, children: new Date(meeting.date).toLocaleDateString() }), _jsx(Link, { to: `/meetings/${meeting.id}`, className: "w-full py-1.5 sm:py-2 text-sm sm:text-base rounded-lg border border-primary text-primary transition hover:bg-primary hover:text-base-100 text-center", style: { backgroundColor: "transparent" }, children: "View Details" })] }, meeting.id))) })] }), _jsxs(motion.section, { className: "py-8 px-4 sm:py-10 sm:px-6 text-center", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0, transition: { duration: 0.8 } }, children: [_jsx("h2", { className: "text-2xl sm:text-3xl font-bold mb-3 sm:mb-4", style: { color: theme.primary }, children: "Stay Informed" }), _jsx("p", { className: "mb-3 sm:mb-4 text-sm sm:text-base", style: { color: theme.secondary }, children: "Get quick access to the latest meetings anytime." }), _jsx(Link, { to: "/meetings", className: "px-4 py-2 sm:px-6 sm:py-3 text-base sm:text-lg font-semibold rounded-lg transition hover:brightness-90", style: { backgroundColor: theme.primary, color: theme["base-100"] }, children: "View All Meetings" })] })] }));
};
export default LandingPage;
